name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies and build the project
      - name: Install Dependencies and Build
        env:
          VITE_APP_AWS_S3_BUCKET: ${{ secrets.VITE_APP_AWS_S3_BUCKET }}
          VITE_APP_AWS_REGION: ${{ secrets.VITE_APP_AWS_REGION }}
          VITE_APP_AWS_ACCESS_KEY_ID: ${{ secrets.VITE_APP_AWS_ACCESS_KEY_ID }}
          VITE_APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.VITE_APP_AWS_SECRET_ACCESS_KEY }}
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
        run: |
          npm ci
          npm run build

      # Step 4: Rename dist folder for deployment
      - name: Rename dist to hef-frontend
        run: mv ./dist ./hef-frontend

      # Step 5: SSH into EC2 and prepare for deployment
      - name: Clean Temporary Directory on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Remove old temp directory if it exists
            rm -rf ~/deploy-temp
            mkdir ~/deploy-temp

      # Step 6: Copy built files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./hef-frontend/
          target: ~/deploy-temp/

      # Step 7: Deploy files and restart Nginx
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Remove old deployment
            sudo rm -rf /usr/share/nginx/html/hef-frontend

            # Move new files to the deployment directory
            sudo mv ~/deploy-temp/* /usr/share/nginx/html/hef-frontend

            # Remove temporary deployment folder
            sudo rm -rf ~/deploy-temp

            # Set proper permissions
            sudo chown -R www-data:www-data /usr/share/nginx/html/hef-frontend
            sudo chmod -R 755 /usr/share/nginx/html/hef-frontend

            # Restart NGINX to apply changes
            sudo systemctl restart nginx
